/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 63
#define YY_END_OF_BUFFER 64
static yyconst short int yy_accept[233] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   64,   62,
       41,    1,   20,   57,   26,   62,   62,   32,   33,   25,
       38,   25,   62,   26,   21,   39,   29,   30,   29,   40,
       36,   37,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   34,   62,   35,   50,   51,
       50,   54,   55,   61,   59,   60,   61,   41,   29,    0,
       56,   31,   47,    0,    0,   27,   28,   48,    0,   49,
       53,    0,    0,   21,   45,   45,   45,    0,   40,   40,
       40,   40,   40,   40,   40,    6,   40,   40,   40,    3,
       40,   40,   40,   40,   40,   40,   40,   52,   58,   23,

        0,    0,   48,   48,    0,    0,   22,    0,   21,   45,
       45,   45,   45,   45,   44,   44,   44,   22,   44,   44,
       44,   45,   45,   40,   40,   40,   40,   40,   40,   40,
       40,    5,    9,   40,   40,   40,   40,   40,   40,   46,
       24,   48,    0,    0,   43,    0,   43,   44,   22,   45,
       43,   44,   22,   44,    0,    0,   22,   45,   45,   45,
       44,   43,   44,   45,   43,   40,   15,   10,   40,   40,
       40,    4,   40,   19,   40,   40,   40,   13,   40,   44,
       44,   44,   22,   44,   22,   22,   44,   22,   42,   42,
       22,   42,   42,   42,   44,    8,   40,   40,   40,   12,

       40,   40,   40,    7,   44,   44,   44,   48,   22,    0,
       22,   22,   44,   22,   42,   44,   40,   40,   11,   40,
       14,   16,   42,   42,   22,   22,   42,   40,   17,    2,
       18,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,    1,   19,   20,
       21,   22,    1,    1,   23,   23,   23,   23,   24,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       25,   26,   27,    1,   28,    1,   29,   30,   31,   32,

       33,   34,   23,   35,   36,   23,   37,   38,   39,   40,
       41,   42,   23,   43,   44,   45,   46,   47,   48,   23,
       23,   23,   49,   50,   51,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[52] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    5,    1,    6,    7,    1,    1,
        1,    1,    7,    7,    1,    8,    1,    9,    6,    6,
        7,    7,    7,    6,    7,    7,    7,    7,    7,    6,
        7,    7,    6,    7,    6,    7,    6,    7,    1,    3,
        1
    } ;

static yyconst short int yy_base[249] =
    {   0,
        0,    0,   49,   50,  359,  355,   51,   52,  344,  963,
      340,  963,  318,  329,  963,  325,   55,  963,  963,  318,
      963,  306,  295,   48,   81,  963,  287,  281,  275,   47,
      963,  963,    0,  118,  119,  122,  121,  124,  130,   51,
      123,  141,  125,  152,  153,  963,  243,  963,  963,  963,
      268,  963,  963,  963,  963,  963,  266,  263,  963,  203,
      191,  963,  963,   60,    0,  963,  963,  172,  164,  963,
      963,   52,  160,  165,  177,  205,  173,  161,   56,    0,
      170,  242,  171,  243,  244,  245,  246,  247,  129,  248,
      249,  251,  253,  252,  267,  270,  277,  963,  963,  963,

       64,  163,  128,  120,  283,  297,  301,  309,  311,  319,
      323,  284,  331,    0,   56,  124,  335,  359,  396,  337,
      339,  398,  409,  402,  289,  397,  404,  405,  413,  414,
      422,  420,  424,  429,  430,  431,  438,  439,  440,  963,
      963,   50,  462,  443,  445,  483,  520,  447,  455,  527,
      190,  464,  525,  531,  535,  539,  541,  548,  555,  546,
      563,  570,  553,  588,  568,  546,  540,  563,  625,  626,
      627,  628,  629,  630,  631,  632,  635,  634,  636,  650,
      653,  662,  666,  670,  674,  676,  698,  700,  702,  706,
      708,  715,  713,  717,  723,  658,  757,  758,  759,  721,

      760,  761,  765,  762,  725,  727,  733,  764,  766,  787,
      777,  789,  791,  793,  795,  799,  799,  803,  763,  806,
      805,  807,  806,  811,  819,  821,  823,  827,  815,  829,
      834,  963,  862,  871,  880,  889,  897,  901,  904,  908,
      916,  921,  925,  928,  932,  937,  944,  953
    } ;

static yyconst short int yy_def[249] =
    {   0,
      232,    1,  233,  233,  234,  234,  235,  235,  232,  232,
      232,  232,  232,  236,  232,  232,  237,  232,  232,  232,
      232,  232,  238,  232,  232,  232,  232,  232,  232,  239,
      232,  232,  240,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  236,
      236,  232,  232,  241,  242,  232,  232,  243,  238,  232,
      232,  232,  238,   25,  244,  232,  245,  238,  239,  240,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  232,  232,  232,

      241,  232,  246,  243,  232,  232,  238,  238,   25,   76,
      244,  244,  244,  245,  232,  247,  238,  232,  244,  113,
      245,  245,  245,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  232,
      232,  246,  247,  232,  232,  232,  238,  247,  118,   76,
      113,  232,  248,  238,  232,  238,  118,  113,   76,  245,
      113,  113,  245,  232,  245,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  247,
      248,  243,  248,  238,  248,  118,  118,  248,  232,  238,
      118,  113,  118,  245,  118,  239,  239,  239,  239,  239,

      239,  239,  239,  239,  248,  248,  243,  243,  183,  238,
      248,  118,  118,  248,  118,  195,  239,  239,  239,  239,
      239,  239,  248,  243,  183,  248,  195,  239,  239,  239,
      239,    0,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232
    } ;

static yyconst short int yy_nxt[1015] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       15,   20,   21,   22,   23,   24,   25,   25,   26,   27,
       28,   29,   30,   30,   31,   10,   32,   33,   30,   34,
       35,   36,   37,   38,   30,   39,   30,   30,   40,   30,
       30,   41,   42,   43,   30,   30,   44,   45,   46,   47,
       48,   50,   50,   55,   55,   56,   56,   63,   70,   51,
       51,   78,   63,   71,   68,   78,   63,  100,  105,  105,
       78,  140,  152,  152,   80,  106,   57,   57,   80,   92,
       65,   72,   72,   80,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   73,   72,   74,   74,   72,

       72,   72,   72,   75,   76,   72,   72,   72,   77,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   72,
       72,   72,   78,   78,  103,   78,   78,   78,   78,   78,
      153,  153,   68,   78,   78,   80,   80,   82,   80,   80,
       80,   80,   80,   83,   85,   78,   80,   80,   87,   84,
       81,   88,   86,   90,   89,   93,   78,   78,   80,   91,
      141,  132,   95,   94,   68,   68,  107,  107,   68,   80,
       80,  109,  109,  108,   78,   78,  103,   97,  110,  122,
      122,   78,   96,  111,  111,   61,  123,   80,   80,  126,

      113,  232,  124,  232,  114,  115,  115,   61,  115,  115,
      115,  115,  115,  115,  115,  115,  116,  115,  116,  117,
      115,  118,  118,  115,  115,  115,  115,  119,  120,  115,
      115,  115,  121,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  115,  115,  115,   78,   78,   78,   78,
       78,   78,   78,   78,   58,   78,   78,   78,   99,   80,
       80,   80,   80,   80,   80,   80,   80,  128,   80,   80,
       80,   78,  127,   98,   78,  125,  134,  131,  135,  130,
      129,   78,   62,  133,   80,   59,  136,   80,   78,  105,

      105,   59,  137,   78,   80,  138,  143,   59,  144,   68,
      144,  114,  139,  145,  145,   68,   80,  107,  107,   67,
      144,  167,  144,   68,  146,  147,  147,  109,  109,   66,
      148,   62,  148,   61,  110,  149,  149,   78,   59,  111,
      111,   58,  144,  232,  144,   78,  150,  151,  151,   68,
      114,  154,  154,  162,  162,  163,  163,   53,  114,  155,
      155,   53,  155,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  156,  155,  157,  157,  155,  155,  155,
      155,  158,  159,  155,  155,  155,  160,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,

      158,  158,  158,  158,  158,  158,  158,  155,  155,  155,
       78,   78,  161,  161,  122,  122,   78,  232,   78,   78,
      144,  164,  144,  114,   80,  165,  165,   78,   78,   80,
      166,   80,   80,  170,   78,  232,   78,  232,   78,  168,
       80,   80,  171,   78,   78,   78,  172,   80,  169,   80,
      173,   80,   78,   78,   78,  232,   80,   80,   80,  145,
      145,  145,  145,  185,  185,   80,   80,   80,  174,  175,
      178,  186,  186,  180,  232,  180,  176,  179,  181,  181,
      152,  152,  177,  115,  115,  232,  115,  115,  115,  115,
      115,  115,  115,  115,  116,  115,  116,  182,  115,  183,

      183,  115,  115,  115,  115,  184,  184,  115,  115,  115,
      115,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  115,  115,  115,   68,  232,  147,  147,  180,  232,
      180,  188,  188,  187,  187,   68,  232,  154,  154,  232,
      119,  189,  189,   68,   78,  190,  190,  191,  191,  232,
       78,  232,  194,  194,  192,  192,  180,   80,  180,  163,
      163,  193,  193,   80,  232,  232,  232,   78,  119,  161,
      161,  232,  196,  232,  165,  165,  162,  162,  115,  115,
       80,  115,  115,  115,  115,  115,  115,  115,  115,  180,

      115,  180,  115,  115,  195,  195,  115,  115,  115,  115,
      121,  121,  115,  115,  115,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  115,  115,  115,   78,
       78,   78,   78,   78,   78,   78,   78,  232,   78,   78,
       78,  232,   80,   80,   80,   80,   80,   80,   80,   80,
      197,   80,   80,   80,  199,  203,  205,  205,  204,  206,
      206,  198,   78,  200,  202,  201,  103,  232,  207,  207,
      208,  232,  209,  209,   68,   80,  154,  154,  210,  210,
      211,  211,  212,  212,  210,  210,  210,  210,  210,  210,

      210,  210,  210,  210,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  210,  213,  213,  214,  214,  189,  189,
       68,  158,  190,  190,  191,  191,  232,  232,  232,  215,
      215,  192,  192,  194,  194,   78,  158,  155,  232,  216,
      216,  206,  206,  223,  223,  160,  160,  103,   80,  207,
      207,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      160,   78,   78,   78,   78,   78,   78,   78,  103,   78,
      224,  224,  225,  225,   80,   80,   80,   80,   80,   80,
       80,  219,   80,  226,  226,  218,  217,  220,  232,  222,

      221,   68,  232,  190,  190,  212,  212,  215,  215,  214,
      214,  215,  215,   78,  158,  227,  227,   78,  158,   78,
       78,   78,  223,  223,  232,  103,   80,  224,  224,   78,
       80,  232,   80,   80,   80,  225,  225,  226,  226,  227,
      227,   78,   80,   78,  228,  230,  232,  229,   78,  232,
      232,  232,  232,  232,   80,  232,   80,  232,  232,  231,
      232,   80,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   60,
      232,   60,   60,   60,   60,   60,   60,   60,   64,  232,

      232,  232,   64,   64,   64,   69,   69,   69,   79,   79,
       79,  232,   79,   80,   80,  232,   80,  101,  232,  101,
      232,  101,  101,  102,  232,  232,  102,  232,  102,  104,
      104,  104,  112,  112,  112,  232,  112,  114,  114,  232,
      114,  142,  142,  142,  115,  232,  115,  115,  115,  115,
      115,  115,  115,  155,  232,  155,  155,  155,  155,  155,
      155,  155,    9,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,

      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232
    } ;

static yyconst short int yy_chk[1015] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    7,    8,    7,    8,   17,   24,    3,
        4,   30,   64,   24,  142,   40,  101,   64,   72,   72,
       79,  101,  115,  115,   30,   72,    7,    8,   40,   40,
       17,   25,   25,   79,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,

       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   34,   35,  104,   37,   36,   41,   38,   43,
      116,  116,  103,   89,   39,   34,   35,   35,   37,   36,
       41,   38,   43,   35,   36,   42,   89,   39,   37,   35,
       34,   38,   36,   39,   38,   41,   44,   45,   42,   39,
      102,   89,   43,   42,   73,   78,   73,   73,   69,   44,
       45,   74,   74,   73,   81,   83,   68,   45,   74,   77,
       77,   75,   44,   75,   75,   61,   77,   81,   83,   83,

       75,  151,   81,  151,   75,   76,   76,   60,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   82,   84,   85,   86,
       87,   88,   90,   91,   58,   92,   94,   93,   57,   82,
       84,   85,   86,   87,   88,   90,   91,   85,   92,   94,
       93,   95,   84,   51,   96,   82,   92,   88,   93,   87,
       86,   97,   47,   91,   95,   29,   94,   96,  112,  105,

      105,   28,   95,  125,   97,   96,  105,   27,  106,   23,
      106,  112,   97,  106,  106,  107,  125,  107,  107,   22,
      108,  125,  108,  108,  107,  108,  108,  109,  109,   20,
      110,   16,  110,   14,  109,  110,  110,  111,   13,  111,
      111,   11,  113,    9,  113,  113,  111,  113,  113,  117,
      111,  117,  117,  120,  120,  121,  121,    6,  113,  118,
      118,    5,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,

      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      119,  126,  119,  119,  122,  122,  124,    0,  127,  128,
      123,  122,  123,  119,  126,  123,  123,  129,  130,  124,
      124,  127,  128,  128,  132,    0,  131,    0,  133,  126,
      129,  130,  129,  134,  135,  136,  130,  132,  127,  131,
      131,  133,  137,  138,  139,    0,  134,  135,  136,  144,
      144,  145,  145,  148,  148,  137,  138,  139,  134,  135,
      138,  149,  149,  143,    0,  143,  136,  139,  143,  143,
      152,  152,  137,  146,  146,    0,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,

      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  147,    0,  147,  147,  150,    0,
      150,  153,  153,  150,  150,  154,    0,  154,  154,    0,
      150,  155,  155,  156,  167,  156,  156,  157,  157,  158,
      166,  158,  160,  160,  158,  158,  159,  167,  159,  163,
      163,  159,  159,  166,  161,    0,  161,  168,  159,  161,
      161,  162,  166,  162,  165,  165,  162,  162,  164,  164,
      168,  164,  164,  164,  164,  164,  164,  164,  164,  164,

      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  169,
      170,  171,  172,  173,  174,  175,  176,    0,  178,  177,
      179,    0,  169,  170,  171,  172,  173,  174,  175,  176,
      169,  178,  177,  179,  171,  177,  180,  180,  179,  181,
      181,  170,  196,  173,  176,  175,  182,    0,  182,  182,
      183,    0,  183,  183,  184,  196,  184,  184,  183,  183,
      185,  185,  186,  186,  183,  183,  183,  183,  183,  183,

      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  187,  187,  188,  188,  189,  189,
      190,  187,  190,  190,  191,  191,  192,    0,  192,  193,
      193,  192,  192,  194,  194,  200,  193,  195,    0,  195,
      195,  205,  205,  206,  206,  195,  195,  207,  200,  207,
      207,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  197,  198,  199,  201,  202,  204,  219,  208,  203,
      208,  208,  209,  209,  197,  198,  199,  201,  202,  204,
      219,  199,  203,  211,  211,  198,  197,  201,    0,  203,

      202,  210,    0,  210,  210,  212,  212,  213,  213,  214,
      214,  215,  215,  217,  213,  216,  216,  218,  215,  221,
      220,  222,  223,  223,    0,  224,  217,  224,  224,  229,
      218,    0,  221,  220,  222,  225,  225,  226,  226,  227,
      227,  228,  229,  230,  217,  220,    0,  218,  231,    0,
        0,    0,    0,    0,  228,    0,  230,    0,    0,  228,
        0,  231,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  236,
        0,  236,  236,  236,  236,  236,  236,  236,  237,    0,

        0,    0,  237,  237,  237,  238,  238,  238,  239,  239,
      239,    0,  239,  240,  240,    0,  240,  241,    0,  241,
        0,  241,  241,  242,    0,    0,  242,    0,  242,  243,
      243,  243,  244,  244,  244,    0,  244,  245,  245,    0,
      245,  246,  246,  246,  247,    0,  247,  247,  247,  247,
      247,  247,  247,  248,    0,  248,  248,  248,  248,  248,
      248,  248,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,

      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1305115.l"
#define INITIAL 0
#define COMMENT 1

#define SCOMMENT 2

#define MULTISTRING 3

#line 8 "1305115.l"

#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include "1305115_table.h"
#include "y.tab.h"

using namespace std;


extern YYSTYPE yylval;
extern symbolTable* table;
extern symbolTable* globaltable;
extern int globalflag;
void yyerror(const char *);

char c[1000000];
int start_l=0;
int line=1;
int error=0;
int i=0;
int j=0;
int check;

#line 701 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 40 "1305115.l"

#line 854 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 233 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 963 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 41 "1305115.l"
{//printf("newline is found\n"); 
//printf("new line is found\n");
line++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 45 "1305115.l"
{return PRINTLN; //newly added
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 48 "1305115.l"
{return IF;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 50 "1305115.l"
{return ELSE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 52 "1305115.l"
{return FOR;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 54 "1305115.l"
{return 	DO;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 56 "1305115.l"
{return WHILE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 58 "1305115.l"
{return BREAK;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 60 "1305115.l"
{return INT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 62 "1305115.l"
{return CHAR;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 64 "1305115.l"
{return DOUBLE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 66 "1305115.l"
{return FLOAT;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 68 "1305115.l"
{return VOID;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 70 "1305115.l"
{return RETURN;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 72 "1305115.l"
{return CASE;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 74 "1305115.l"
{return SWITCH;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 76 "1305115.l"
{return DEFAULT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 78 "1305115.l"
{return CONTINUE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 80 "1305115.l"
{return MAIN; //NEWLY ADDED
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 83 "1305115.l"
{return NOT; //NEWLY ADDED
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 86 "1305115.l"
{//insertion
symbolInfo *s= new  symbolInfo(yytext, "CONST_INT",0);
s->val.i=atoi(yytext);
s->data=integer;
yylval = (YYSTYPE)s;
return CONST_INT;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 94 "1305115.l"
{// .90875 is not taken as a float but 0.90875 is taken??
symbolInfo *s= new  symbolInfo(yytext, "CONST_FLOAT",0);
s->val.f=atof(yytext);
s->data=floating;
yylval = (YYSTYPE)s;
return CONST_FLOAT;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 102 "1305115.l"
{
symbolInfo *s= new  symbolInfo(yytext, "CONST_CHAR",0);//problem as it is multi character for having quotation
yylval = (YYSTYPE)s;
s->data=character;
s->val.c=yytext[1];
printf("\nin l file %c %c\n",yytext[1],s->val.c);
return CONST_CHAR;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 111 "1305115.l"
{
symbolInfo *s= new  symbolInfo(yytext,"CONST_CHAR",0);
yylval = (YYSTYPE)s;
s->data=character;
return CONST_CHAR;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 118 "1305115.l"
{
symbolInfo *s= new  symbolInfo(yytext, "ADDOP",0);
yylval = (YYSTYPE)s;
return ADDOP;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 124 "1305115.l"
{
symbolInfo *s= new  symbolInfo(yytext, "MULOP",0);
yylval = (YYSTYPE)s;
return MULOP;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 130 "1305115.l"
{//WHY NOT (++|--)
symbolInfo *s= new  symbolInfo(yytext, "INCOP",0);
yylval = (YYSTYPE)s;
return INCOP;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 136 "1305115.l"
{//WHY NOT (++|--) //NEWLY ADDED
symbolInfo *s= new  symbolInfo(yytext, "DECOP",0);
yylval = (YYSTYPE)s;
return DECOP;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 142 "1305115.l"
{
symbolInfo *s= new  symbolInfo(yytext, "RELOP",0);
yylval = (YYSTYPE)s;
return RELOP;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 148 "1305115.l"
{return ASSIGNOP;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 150 "1305115.l"
{ // CHANGED // PREVIOUS "&&"|"||"|"!" 
symbolInfo *s= new  symbolInfo(yytext, "LOGICOP",0);
yylval = (YYSTYPE)s;
return LOGICOP;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 156 "1305115.l"
{return LPAREN;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 158 "1305115.l"
{return RPAREN;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 160 "1305115.l"
{return LCURL;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 162 "1305115.l"
{return RCURL;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 164 "1305115.l"
{return LTHIRD;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 166 "1305115.l"
{return RTHIRD;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 168 "1305115.l"
{return COMMA;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 170 "1305115.l"
{return SEMICOLON;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 172 "1305115.l"
{//whether _A_b_c is a variable or not
if(globalflag==0){
	//printf("in local scope\n");
	symbolInfo *s;
	s= table->lookOut(yytext);
		if(s==Null)
			{				
			s= new symbolInfo(yytext, "ID",0);
			printf("%s\n",s->name.c_str());	
			}
		yylval = (YYSTYPE)s;
		}
else
{
	//printf("in global scope\n");
	symbolInfo *s1;
	s1= globaltable->lookOut(yytext);
		if(s1==Null)
			{						
			s1= new symbolInfo(yytext, "ID",0);
			printf("%s\n",s1->name.c_str());
			}
	yylval = (YYSTYPE)s1;
}

return ID;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 200 "1305115.l"
{
//may be for whitespace is ignored 
//printf("white space is found\n");
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 205 "1305115.l"
{//for 10.2E0.5675 but not 10.2 E .34567 // \.

error++;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 210 "1305115.l"
{//for 12.E // for\.

error++;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 214 "1305115.l"
{//for 12E.12345 //problem for\.

error++;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 219 "1305115.l"
{//12abdc
printf("invalid prefix in id,%s\n",yytext);
error++;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 224 "1305115.l"
{//'abc'

error++;
}
	YY_BREAK
case 47:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 228 "1305115.l"
{

error++;
//line++;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 234 "1305115.l"
{//1.2.3 123.45.667 .... a.s.f.g

error++;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 239 "1305115.l"
{	//for multiline comment state
	i=0;
	start_l=line;
	BEGIN COMMENT;
	printf("comment is started \n");
	//fprintf(logout,"Line no %d:Token <COMMENT> lexeme %s",line,yytext);
	while(yytext[j]!='\0'){
		c[i]=yytext[j];
	i++;j++;
	}
	j=0;
	//c[i]=yytext;
	//i++;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 253 "1305115.l"
{//fprintf(logout,"%s",yytext);
	while(yytext[j]!='\0'){
		c[i]=yytext[j];
	i++;j++;
	}
	j=0;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 260 "1305115.l"
{line++;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 262 "1305115.l"
{
	printf("comment is ended \n");
	while(yytext[j]!='\0'){
		c[i]=yytext[j];
	i++;j++;
	}
	j=0;
	while(i!=0){
		c[i]=0;
	i--;
	}
	BEGIN INITIAL;
	i=0;
}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 276 "1305115.l"
{//for unfinished comment
	error++;
	printf("no end of comment %s\n",yytext);
	yyterminate();
	i=0;
	//for unfinished comment
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 284 "1305115.l"
{//for singleline comment 
	BEGIN SCOMMENT;
	printf("single line comment is started\n");
	//fprintf(logout,"Line no %d:Token <COMMENT> lexeme %s",line,yytext);
	//i=0;
	while(yytext[j]!='\0'){
		c[i]=yytext[j];
	i++;j++;
	}
	j=0;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 295 "1305115.l"
{//fprintf(logout,"%s",yytext);
	while(yytext[j]!='\0'){
		c[i]=yytext[j];
	i++;j++;
	}
	j=0;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 302 "1305115.l"
{
	j=0;
	line++; 
	
	while(i!=0){
		c[i]=0;
	i--;
	}
	BEGIN INITIAL;
	//end of single line comment
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 316 "1305115.l"
{//single line string
	
	//s.insertItem(yytext,"STRING");
	//return STRING; //NEWLY ADDED
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 322 "1305115.l"
{	//both for multi line string
	start_l=line;
	BEGIN MULTISTRING;
	while(yytext[j]!='\0'){
		c[i]=yytext[j];
	i++;j++;
	}
	j=0;
	printf("start of a string %s\n",yytext);
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 332 "1305115.l"
{
	printf("newline in string is found");
	while(yytext[j]!='\0'){
		c[i]=' ';
	i++;j++;
	}
	j=0;
	line++;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 341 "1305115.l"
{
	
	while(i!=0){
		c[i]=0;
	i--;
	}
	line++;
	error++;
	BEGIN INITIAL;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 352 "1305115.l"
{
	printf("\nstring is ended %s\n",yytext);
	while(yytext[j]!='\0'){
		c[i]=yytext[j];
	i++;j++;
	}
	j=0;
	
	//s.insertItem(c,"STRING");
	//return STRING; //NEWLY ADDED
	while(i!=0){
		c[i]=0;
	i--;
	}
	BEGIN INITIAL;
	//end of string	
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 369 "1305115.l"
{
	printf("%s",yytext);
	while(yytext[j]!='\0'){
		c[i]=yytext[j];
	i++;j++;
	}
	j=0;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 377 "1305115.l"
{

error++;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 386 "1305115.l"
ECHO;
	YY_BREAK
#line 1484 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SCOMMENT):
case YY_STATE_EOF(MULTISTRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 233 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 233 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 232);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 386 "1305115.l"
